---
title: "admixr - R package for performing ADMIXTOOLS analyses from within R"
author:
  - Martin Petr, Janet Kelso
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Abstract

We present a new package for the R programming language that provides convenient
wrappers for ADMIXTOOLS command-line utilities and completely abstract away all
technical details
This package not only drastically reduces the amount of code needed to perform
population genetic analyses, but presents a significant improvement for reproducible
research by making it possible to build fully automatic analytic pipelines.

## Introduction

## Implementation

The `admixr` is implemented in the R programming language. The main interface
for the user consists of several R functions.

Generally, performing even the most trivial analysis using the ADMIXTOOLS package
presents a significant amount of work for the user. For example, in order to
calculate $D$ statistic such as $D(W, X, Y, Z)$, the user needs to do the following:


## Examples
## Conclusion