// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// vcf_to_eigenstrat
void vcf_to_eigenstrat(const char* vcf, const char* eigenstrat);
RcppExport SEXP _admixr_vcf_to_eigenstrat(SEXP vcfSEXP, SEXP eigenstratSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const char* >::type vcf(vcfSEXP);
    Rcpp::traits::input_parameter< const char* >::type eigenstrat(eigenstratSEXP);
    vcf_to_eigenstrat(vcf, eigenstrat);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_admixr_vcf_to_eigenstrat", (DL_FUNC) &_admixr_vcf_to_eigenstrat, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_admixr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
