# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Convert VCF file into an EIGENSTRAT format
#'
#' @param vcf A path to a VCF file.
#' @param eigenstrat A path to an output EIGENSTRAT triplet.
#'
#' @export
#'
vcf_to_eigenstrat <- function(vcf, eigenstrat) {
    invisible(.Call(`_admixr_vcf_to_eigenstrat`, vcf, eigenstrat))
}

