#' Generate a file with populations for a qpF4ratio run.
#'
#' @description For details about the format of the population list
#'     file see documentation of the ADMIXTOOLS package.
#' 
#' @param X, A, B, C, O Population names, using the terminology of
#'     Patterson et al., 2012
#' @param file Path to the poplist file that will be generated.
#' @export
create_qpF4ratio_pop_file <- function(X, A, B, C, O, file) {
    lines <- sprintf("%s %s : %s %s :: %s %s : %s %s", A, O, X, C, A, O, B, C)
    writeLines(lines, file)
}


#' Generate a file with populations for a qpF4ratio run.
#'
#' @description For details about the format of the population list
#'     file see documentation of the ADMIXTOOLS package.
#'
#' @param X, A, B, C, O Population names, using the terminology of
#'     Patterson et al., 2012. It is possible to specify vectors of
#'     population identifiers as W, X, etc. That way, all possible
#'     combinations of specified W, X, Y and Z quadruples will be
#'     generated.
#' @param poplist List of populations. It will be saved as a file, one
#'     population per line.
#' @param file Path to the poplist file that will be generated.
#' @export
create_Dstats_pop_file <- function(W=NULL, X=NULL, Y=NULL, Z=NULL, poplist=NULL, file) {
    if (all(!is.null(c(W, X, Y, Z)))) { # individual populations were specified
        lines <- c()
        for (w in W) for (x in X) for (y in Y) for (z in Z) {
            lines <- c(lines, sprintf("%s %s %s %s", w, x, y, z))
        }
    } else if (!is.null(poplist)) { # a simple list of populations was specified
        lines <- poplist
    } else { # missing population information
        stop("Population identifiers must be specified")
    }

    writeLines(lines, file)
}


#' Generate a parameter file.
#'
#' @param par_file Path to the parameter file generated by this
#'     function.
#' @param pop_file Populations file (qpDstat quadruples, Dstats
#'     population list, qpF4ratio populations, etc.).
#' @param eigenstrat_prefix Prefix of the geno/snp/ind files (can
#'     include the path). If specified, geno_file/snp_file/ind_file
#'     will be ignored.
#' @param geno_file Path to the genotype file.
#' @param snp_file Path to the snp file.
#' @param ind_file Path to the ind file.
#' @param badsnp_file SNP file with information about ignored sites.
#' @param f4mode Run Dstats with an "f4mode: YES" option, estimating
#'     just the f4?
#' @export
create_par_file <- function(par_file, pop_file,
                            eigenstrat_prefix=NULL,
                            geno_file=NULL, snp_file=NULL, ind_file= NULL,
                            badsnp_file=NULL,
                            f4mode=FALSE) {
    if (all(is.null(c(eigenstrat_prefix, geno_file, snp_file, ind_file)))) {
        stop("Prefix of EIGENSTRAT files or the paths to individual geno/snp/ind files must be specified")
    }

    # if the user specified EIGENSTRAT prefix, set only paths to unspecified geno/snp/ind files
    if (!is.null(eigenstrat_prefix)) {
        if (is.null(geno_file)) geno_file <- paste0(eigenstrat_prefix, ".geno")
        if (is.null(snp_file)) snp_file <- paste0(eigenstrat_prefix, ".snp")
        if (is.null(ind_file)) ind_file <- paste0(eigenstrat_prefix, ".ind")
    }

    writeLines(sprintf("genotypename: %s\nsnpname: %s\nindivname: %s\npopfilename: %s",
                       geno_file, snp_file, ind_file, pop_file),
               con=par_file)

    if (!is.null(badsnp_file)) {
        write(sprintf("badsnpname: %s", badsnp_file), file=par_file, append=TRUE)
    }

    if (f4mode) {
        write("f4mode: YES", file=par_file, append=TRUE)
    }
}


#' Run a given ADMIXTOOLS command.
#'
#' @param tool Which ADMIXTOOLS command to run. At the moment, only
#'     qpDstat and qpF4ratio are supported.
#' @param par_file Path to the parameter file.
#' @param log_file Path to the output file. If NULL, output will be
#'     printed to stdout.
#' @export
run_cmd <- function(cmd, par_file, log_file) {
    if (!cmd %in% c("qpDstat", "qpF4ratio")) {
        stop("ADMIXTOOLS command '", cmd, "' is not supported or does not exist")
    }

    system(paste(cmd, "-p", par_file, ">", log_file))
}


# Create either specified or a temporary directory.
get_dir <- function(dir_name=NULL) {
    if (!is.null(dir_name)) {
        dir.create(dir_name, showWarnings=FALSE)
    } else {
        dir_name <- tempdir()
    }

    dir_name
}


# Generate paths to the population file, parameter file and log file
# based on a specified directory.
get_files <- function(dir_name, prefix) {
    directory <- get_dir(dir_name)
    list(
        pop_file=file.path(directory, paste0(prefix, ".pop")),
        par_file=file.path(directory, paste0(prefix, ".par")),
        log_file=file.path(directory, paste0(prefix, ".log"))
    )
}

# Check for the presence of a given set of labels in an 'ind' file.
# Fail if there a sample was not found.
check_presence <- function(labels, prefix=NULL, ind=NULL) {
    path <- ifelse(!is.null(prefix), paste0(prefix, ".ind"), ind)
    not_present <- setdiff(labels, suppressMessages(read_ind(path)$label))

    if (length(not_present) > 0) {
        stop("The following samples are not present in the 'ind' file: ",
             paste(not_present, collapse=", "))
    }
}
